# Generated by Django 2.0.3 on 2018-05-24 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usos_id', models.CharField(default=None, max_length=32, null=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='SubjectComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
            options={
                'verbose_name': 'Subject comment',
                'verbose_name_plural': 'Subject comments',
            },
        ),
        migrations.CreateModel(
            name='SubjectExact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('WYK', 'Wykład'), ('CW', 'Ćwiczenia'), ('LAB', 'Laboratorium')], default=None, max_length=3, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
            options={
                'verbose_name': 'Exact subject',
                'verbose_name_plural': 'Exact subjects',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('firstname', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('usos_id', models.IntegerField(primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('wikispaces', models.BooleanField(default=False)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('subject_exact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubjectExact')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher')),
            ],
            options={
                'verbose_name': 'Teacher comment',
                'verbose_name_plural': 'Teacher comments',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TeacherComment'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject_exact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SubjectExact'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('teacher', 'subject_exact')},
        ),
    ]
