# Generated by Django 2.0.3 on 2019-05-18 17:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='ects',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='groups',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='language',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='period',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='types',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
    ]
