# Generated by Django 2.0.3 on 2019-05-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190518_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='ects',
            field=models.FloatField(default=None, null=True),
        ),
    ]
