# Generated by Django 2.0.3 on 2019-05-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190518_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='types',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
