# Generated by Django 2.0.3 on 2019-05-18 18:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190518_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='groups',
            new_name='groups_of_courses',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='types',
            new_name='type_of_course',
        ),
        migrations.AddField(
            model_name='subject',
            name='types_of_classes',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
    ]
